version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: gradle
    directory: /ms-cliente-crud
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /web-cliente-crud
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
